#/usr/bin/env python
# -*- coding: utf-8 -*-
db_data = {'cc':
                [{'CampaignID' : 'cc',
                 'ProdType'   : 'cc',
                 'PID'        : 'H123456789',
                 'CustName'   : 'Watermelon Wang',
                 'MP1'        : '0930624510',
                 'MP2'        : '0930624510',
                 'O1'         : '',
                 'O2'         : '',
                 'H1'         : '',
                 'H2'         : '',
                 'H3'         : '',
                 'H4'         : '',     
                 '連絡人電話一': '',
                 '戶籍1'      : ''
                },
                {'CampaignID' : 'cc',
                 'ProdType'   : 'cc',
                 'PID'        : 'H123456790',
                 'CustName'   : 'Apple Chien',
                 'MP1'        : '0930624511',
                 'MP2'        : '0930624511',
                 'O1'         : '',
                 'O2'         : '',
                 'H1'         : '',
                 'H2'         : '',
                 'H3'         : '',
                 'H4'         : '',     
                 '連絡人電話一': '',
                 '戶籍1'      : ''
                }],
            'gm':
                 [{'CampaignID' : 'gm',
                 'ProdType'   : 'gm',
                 'PID'        : 'H123456789',
                 'CustName'   : 'Guava Fu',
                 'MP1'        : '0930624510',
                 'MP2'        : '0930624510',
                 'O1'         : '',
                 'O2'         : '',
                 'H1'         : '',
                 'H2'         : '',
                 'H3'         : '',
                 'H4'         : '',     
                 '連絡人電話一': '',
                 '戶籍1'      : ''
                },
                {'CampaignID' : 'gm',
                 'ProdType'   : 'gm',
                 'PID'        : 'H123456790',
                 'CustName'   : 'Banana Lin',
                 'MP1'        : '0930624511',
                 'MP2'        : '0930624511',
                 'O1'         : '',
                 'O2'         : '',
                 'H1'         : '',
                 'H2'         : '',
                 'H3'         : '',
                 'H4'         : '',     
                 '連絡人電話一': '',
                 '戶籍1'      : ''
                }],
            }